# -*- coding: utf-8 -*-
"""api.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11f3YVq2pYeacySZxQiTGToeFkn7bgc9G
"""

"""
API para avaliação de indicadores de APS (e-SUS).
Endpoint: POST /avaliar — recebe CSV, retorna análise completa.
"""

import io
import json
import traceback
import pandas as pd
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware

# Importar TODAS as funções do main.py
from main import (
    INDICADORES,
    detectar_indicador,
    preparar_dados,
    definir_boas_praticas,
    verificar_criterios,
    _verificar_criterio_detalhado,
)
app = FastAPI(
    title="API de Avaliação de Indicadores APS",
    description="Avalia boas práticas de Atenção Primária a partir de dados do e-SUS",
    version="2.0.0",
)

# Permitir CORS (para frontend consumir)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def info():
    """Informações da API."""
    return {
        "api": "Avaliação de Indicadores APS",
        "versao": "2.0.0",
        "indicadores_disponiveis": {
            codigo: config["nome"]
            for codigo, config in INDICADORES.items()
        },
        "endpoints": {
            "avaliar": "POST /avaliar (upload CSV)",
            "info": "GET /",
        },
    }

@app.post("/avaliar")
async def avaliar(file: UploadFile = File(...)):
    """
    Recebe um CSV do e-SUS e retorna a avaliação completa.

    - Detecta automaticamente o indicador (C2-C7)
    - Verifica todos os critérios
    - Retorna DataFrame com detalhamento por paciente

    Resposta JSON:
    {
        "indicador": "C3",
        "nome_indicador": "Gestação e Puerpério",
        "total_pacientes": 45,
        "resumo": { ... },
        "pacientes": [ { ... }, { ... } ]
    }
    """
    try:
        # 1. Ler CSV — pular metadata do e-SUS e encontrar cabeçalho real
        conteudo = await file.read()

        # Decodificar
        try:
            texto = conteudo.decode('utf-8-sig')
        except UnicodeDecodeError:
            texto = conteudo.decode('latin-1')

        # Normalizar quebras de linha (\r\n -> \n)
        texto = texto.replace('\r\n', '\n').replace('\r', '\n')
        linhas = texto.split('\n')

        # Detectar separador: analisar a linha com mais separadores
        sep = ';'
        max_seps_global = 0
        for linha in linhas[:50]:
            for candidato in [';', '\t', ',']:
                count = linha.count(candidato)
                if count > max_seps_global:
                    max_seps_global = count
                    sep = candidato

        # Encontrar a linha de cabeçalho real (a com MAIS separadores)
        # O e-SUS exporta centenas de colunas, então o cabeçalho real
        # terá muito mais separadores que qualquer linha de metadata
        header_row = 0
        max_count = 0
        for i, linha in enumerate(linhas[:50]):
            count = linha.count(sep)
            if count > max_count:
                max_count = count
                header_row = i

        import io as io_module
        df = pd.read_csv(
            io_module.StringIO('\n'.join(linhas[header_row:])),
            sep=sep,
            encoding='utf-8',
            on_bad_lines='skip',
            engine='python',
            skip_blank_lines=True
        )

        if df.empty:
            raise HTTPException(status_code=400,
                                detail="CSV vazio ou ilegível")

        # 2. Detectar indicador
        resultado = detectar_indicador(df)
        print(f"\n=== DEBUG detectar_indicador ===")
        print(f"Tipo: {type(resultado)}")
        print(f"Conteúdo: {resultado}")
        print(f"===============================\n")

        if len(resultado) == 3:
            codigo, confianca, razao = resultado
        elif len(resultado) == 2:
            codigo, confianca = resultado
            razao = ""
        else:
            codigo = resultado[0]
            confianca = 0
            razao = ""

        # Garantir que o código seja válido (C2, C3, C4, C5, C6, C7)
        # Se vier apenas "C", tentar extrair de razao ou do print
        if codigo not in INDICADORES:
            # Tentar encontrar padrão C2-C7 no texto
            import re
            match = re.search(r'C[2-7]', str(resultado))
            if match:
                codigo = match.group()
            else:
                raise HTTPException(
                    status_code=422,
                    detail=f"Indicador detectado inválido: '{codigo}'. "
                           f"Esperado: C2, C3, C4, C5, C6 ou C7."
                )

        print(f"\n=== CÓDIGO FINAL: {codigo} ===\n")
            
        # 3. Preparar dados
        dados, colunas_mapeadas = preparar_dados(df, codigo)

        # 4. Verificar critérios
        resultado = verificar_criterios(dados, codigo)

        # 5. Construir resposta
        config = INDICADORES[codigo]
        boas_praticas = definir_boas_praticas(codigo)

        # Resumo estatístico
        resumo = {
            "total_pacientes": len(resultado),
            "em_dia": int((resultado["Nível"] == "EM DIA").sum()),
            "moderado": int((resultado["Nível"] == "MODERADO").sum()),
            "grave": int((resultado["Nível"] == "GRAVE").sum()),
            "muito_grave": int((resultado["Nível"] == "MUITO GRAVE").sum()),
            "critico": int((resultado["Nível"] == "CRÍTICO").sum()),
            "completude_media": round(float(resultado["Completude (%)"].mean()), 1),
            "criterios_avaliados": len(boas_praticas),
        }

        # Lista de pacientes (sem colunas muito longas)
        pacientes = []
        for _, row in resultado.iterrows():
            pacientes.append({
                "nome": row.get("Nome", ""),
                "microarea": row.get("Microárea", ""),
                "idade": row.get("Idade", 0),
                "prioridade": row.get("Prioridade", 0),
                "nivel": row.get("Nível", "N/A"),
                "completude": row.get("Completude (%)", 0),
                "criterios_faltantes": row.get("Critérios Faltantes", 0),
                "detalhamento_faltantes": row.get("Detalhamento Faltantes", "Nenhum"),
                "detalhamento_completo": row.get("Detalhamento Completo", "Sem detalhamento"),
            })

        return JSONResponse({
            "status": "sucesso",
            "indicador": codigo,
            "nome_indicador": config["nome"],
            "confianca_deteccao": f"{float(confianca):.0f}%" if isinstance(confianca, (int, float)) else str(confianca),
            "razao_deteccao": razao,
            "colunas_mapeadas": colunas_mapeadas,
            "criterios_avaliados": [
                {"label": bp["label"],
                 "tipo": bp["tipo"],
                 "descricao_prazo": bp["descricao_prazo"]}
                for bp in boas_praticas
            ],
            "resumo": resumo,
            "pacientes": pacientes,
        })

    except Exception as e:
        print(f"\n=== ERRO ===")
        print(traceback.format_exc())
        print(f"============\n")
        raise HTTPException(
            status_code=500,
            detail=f"Erro interno: {str(e)}\n{traceback.format_exc()}"
        )

@app.get("/indicadores")
def listar_indicadores():
    """Lista todos os indicadores disponíveis."""
    return {
        codigo: {
            "nome": config["nome"],
            "num_boas_praticas": config["num_boas_praticas"],
            "max_prioridade": config["max_prioridade"],
        }
        for codigo, config in INDICADORES.items()
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
